### ISSUE TITLE
Time step size dependency in models

### ISSUE THREAD

**Issue by john-wigg** [Eggeling-Lab-Microscope-Software/TRAIT2D#28]
I was wondering if it was possible to formulate the the models for brownian, confined and hopping diffusion independently of the fixed time step size dt.

Right now, the models contain `i` which can be written as `i = t/dt` where `t` is the time.

Since smart averaging now works regardless of any time step size (see PR #27) this is the last piece of code in the analysis library that still depends on the tracks having a fixed stepsize.

**Comment by FReina** [comment]
Indeed, this is handled in the Minflux branch on my fork. The aim would be to generalize the calculations for non-constant time intervals.

I will add this to the Roadmap for v.2, reference this issue and close it for now.
