### ISSUE TITLE
follow-up work on gui_simulator: secondary issues to consider

### ISSUE THREAD

**Issue by MariiaVision** [Eggeling-Lab-Microscope-Software/TRAIT2D#3]
* [ ] Units type (physical for m/s, digital for px/frame, ...) - discuss with Francesco
* [ ] add info about trajectory
* [ ] Diffusion type could be a dropdown menu
* [ ] Different tabs for trajectory, iscat movie, ... simulations?
* [ ] Add an option to display the hopping map
* [ ] work on GUI layout: Make the input fields and the parameter names closer?
* [ ] Add button to transfer the trajectory simulator to the image sequence parameters
* [ ] Add an option to remove the random seed, because otherwise, the simulation results will be the same every time.
* [ ] Disable the Show Track and Save buttons if no tracks were simulated
* [ ] Add  a progression bar, or notify that the simulation is complete?
* [ ] Simplify parameters name.
* [ ] Add option to remove PSF, and to show that it is loaded.
* [ ] Separate the generate from show image simulation results.
* [ ] Potential problem: The spatial resolution of the PSF and of the simulated movie must be the same.

**Comment by FReina** [comment]
I close this issue as we are planning a full refactor of the simulator in v2 anyway
