### ISSUE TITLE
Wrong y label

### ISSUE THREAD

**Issue by FReina** [Eggeling-Lab-Microscope-Software/TRAIT2D#42]
trait2d/analysis/_adc.py

It prints "Normalized ADC" whereby it should be just "ADC"

**Comment by john-wigg** [comment]
I changed it so that it says "Apparent Diffusion Coeffcient" on single plot (`Track`) and "Average ADC" on the the summary plots (`ListOfTracks`).

Fixed in f6102c7f8f7db2fcaa055c7c0ae1a502bd211648.
