### ISSUE TITLE
Proposing a better MSD calculation

### ISSUE THREAD

**Issue by Zatyrus** [Eggeling-Lab-Microscope-Software/TRAIT2D#52]
While coding my own project I came up with an own version of an MSD calculation that runs significantly faster and tends to be more stable than the one currently implemented.

Used from TRAIT2D
`track.calculate_msd()`

Proposed MSD Calculation
```
from tqdm import tqdm
import numpy as np

def My_MSD(data):
    N = len(data)
    
    col_Array  = np.zeros(N-3)
    
    for i in tqdm(range(1,N-2)):
        col_Array[i-1] = (np.mean(np.sum(np.abs((data[1+i:N,:] - data[1:N - i,:]) ** 2), axis=1)))
        
    return col_Array
```

Analyzing the attached 20000 steps Brownian Diffusion CSV file, the legacy MSD takes about 8.4 seconds and tends to crash for larger tracks. The proposed method takes about 1.1 seconds and runs stable even for tracks as large as 100000 steps (43 seconds). 

Please also view the attached VS_plot.png for result verification created for the Brownian_Diff_20000.csv Dataset.

![MSD_VS_Plot](https://user-images.githubusercontent.com/62382262/139085543-b9ad78fa-2dc5-40d8-afb0-4906796d068d.PNG)
[Brownian_Diff_Test_20000.csv](https://github.com/Eggeling-Lab-Microscope-Software/TRAIT2D/files/7426929/Brownian_Diff_Test_20000.csv)
[Brownian_Diff_Test_100000.csv](https://github.com/Eggeling-Lab-Microscope-Software/TRAIT2D/files/7426930/Brownian_Diff_Test_100000.csv)

**Comment by FReina** [comment]
Will close this when the relative PR is merged

**Comment by FReina** [comment]
This has been now implemented.
